### ISSUE TITLE
Bring hyper to draft-13 of HTTP/2.

### ISSUE THREAD

**Issue by Lukasa** [Lukasa/hyper#63]
Spec is [here](http://tools.ietf.org/html/draft-ietf-httpbis-http2-13). Side-by-side diff is [here](http://tools.ietf.org/rfcdiff?url2=draft-ietf-httpbis-http2-13.txt).

Changes to make:
- [X] Make sure that HEADERS frames with END_STREAM set are allowed to be followed by CONTINUATION frames. (Completed in e59233f1d5bd9dc3a4019099de7df4bac369b545.)
- [X] Receiving frames of unknown type is no longer an error, simply discard them. Log that we did so. (Completed in f229d3781b472e2fd62d31862a95629c7924dd81.)
- [X] Padding has changed again. Update our mixin to cope. (section 6.1) (Completed in a7c42dbcac4dcefaedec49c6687a8aa8168972d6.)
- [X] Data compression was removed. (section 6.1) (Completed in f4cb68e22bf0f3dd22025bd3ef01da1180b672ea.)
- [X] Make sure that we include the padding metadata field in the flow control size. (Completed in 260b4f9cb5de90f8e6fc0d7f07be48375252ad74.)
- [X] Setting IDs are now 16 bit, not 8. (section 6.5.1) (Completed in 34f09a839032a466d4a20b1b925e7e87bb3d7e75.)
- [X] SETTINGS_COMPRESS_DATA is gone. (section 6.5.1) (Completed in f4cb68e22bf0f3dd22025bd3ef01da1180b672ea.)
- [X] CONTINUATION frames can no longer be padded. (Completed in a7c42dbcac4dcefaedec49c6687a8aa8168972d6.)
- [X] The ALT_SVC frame is gone (though it will be in the extension, so maybe don't delete it just yet: instead, start implementing the extension). (I'm leaving the ALT_SVC frame in place, but continuing to track implementing the extension in #30.)
- [X] Allow trailing HEADERS frames (section 8.1). (Completed in 66206300cd93b11906a897e768de5c4f73142680.)
- [X] Discard any header field beginning with a colon other than the understood ones. (Completed in 7be2800ba2d753b2b7cc866fb9ababab5addfc62.)
- [x] "Header fields containing multiple values MUST be concatenated unless the order is known to be insignificant". Work out how we do this. (section 8.1.2.3) (Deferred until a good API can be workshopped, tracked roughly by #36.)
- [x] MUST disable TLS renegotiation. (section 9.2.1) (Appears to be impossible in OpenSSL, so marking as complete.)
- [X] Restricted cipher suites (section 9.2.2) (Deferred, tracked in #64.)
- [X] Bring HPACK to draft 8, see #62. (Completed in cececed4e86f79398e328ef2a582beb27c64db6a.)
- [X] Update hyper NPN/ALPN token to -13. (Completed in 8064e2c7bd4c12bcb0449486e0f3d9dbcdc81683.)
